version: '3'

services:
  auth:
    build:
      context: ./movieCruiserByRohith/AuthSever
    ports:
      - "8081:80"
    depends_on:
      - db
    environment:
      SQLSERVER_AUTH: "Data source=db;Initial catalog=UserDb;User id=sa;Password=P@ssw0rd"
  web:
    build:
      context: ./movieCruiserByRohith/movieCruiserByRohith
    ports:
      - "8089:80"
    links:
      - db
      - auth
    environment:
      SQLSERVER_MOVIE: "Data source=db;Initial catalog=MovieDb;User id=sa;Password=P@ssw0rd"
  ui:
    build:
      context: ./movie-cruiser-capsule-frontend
    ports:
      - "4200:4200"
  db:
    image: "microsoft/mssql-server-windows-express"
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "P@ssw0rd"
      ACCEPT_EULA: "Y"
networks: 
  default:
    external:
      name: nat