export interface Movie {
    movieId: number; //ID returned from TMDb
    id: number; //ID generated by DB
    title: string;
    poster_path: string;
    overview: string;
    released_date: string;
    isWatchlisted: boolean;
    comments: string;
    userId: string;
}